package ni.gob.inss.barista.model.entity.auditoria;

import ni.gob.inss.barista.model.entity.seguridad.Usuario;

import javax.persistence.*;
import java.io.Serializable;
import java.util.*;

/**
 * AuditTrail generated by hbm2java
 * Modificado por jvillanueva el 15/08/2023
 */
@Entity
@Table(name = "audit_trail", schema = "auditoria")
public class AuditTrail implements Serializable {

    private static final long serialVersionUID = 1L;
    @Transient
    List<AuditTrailDetail> auditTrailList = new ArrayList<AuditTrailDetail>();
    @Transient
    String nombreUsuario;
    private long id;
    private String sistema;
    private String modulo;
    private String schema;
    private String tabla;
    private String filaId;
    private String operacion;
    private Date fecha;
    private Usuario usuario;
    private String host;
    private Set<AuditTrailDetail> auditTrailDetails = new HashSet<AuditTrailDetail>(0);


    public AuditTrail() {
    }

    public AuditTrail(long id, String tabla, String operacion, Date fecha,
                      Usuario usuario, String host) {
        this.id = id;
        this.tabla = tabla;
        this.operacion = operacion;
        this.fecha = fecha;
        this.usuario = usuario;
    }

    public AuditTrail(int id, String sistema, String modulo, String tabla, String operacion, Date fecha,
                      Usuario usuario, String filaId, String host,
                      Set<AuditTrailDetail> auditTrailDetails) {
        this.id = id;
        this.sistema = sistema;
        this.modulo = modulo;
        this.tabla = tabla;
        this.operacion = operacion;
        this.fecha = fecha;
        this.usuario = usuario;
        this.filaId = filaId;
        this.host = host;
        this.auditTrailDetails = auditTrailDetails;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Column(name = "\"schema\"", nullable = false, length = 50)
    public String getSchema() {
        return schema;
    }

    public void setSchema(String schema) {
        this.schema = schema;
    }

    @Column(name = "sistema", nullable = false, length = 50)
    public String getSistema() {
        return sistema;
    }

    public void setSistema(String sistema) {
        this.sistema = sistema;
    }

    @Column(name = "modulo", nullable = false, length = 50)
    public String getModulo() {
        return modulo;
    }

    public void setModulo(String modulo) {
        this.modulo = modulo;
    }

    @Column(name = "tabla", nullable = false, length = 50)
    public String getTabla() {
        return this.tabla;
    }

    public void setTabla(String tabla) {
        this.tabla = tabla;
    }

    @Column(name = "operacion", nullable = false, length = 6)
    public String getOperacion() {
        return this.operacion;
    }

    public void setOperacion(String operacion) {
        this.operacion = operacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha", nullable = false, length = 29)
    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @ManyToOne
    @JoinColumn(name = "usuario", nullable = false, referencedColumnName = "username")
    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    @Column(name = "fila_id", length = 10)
    public String getFilaId() {
        return this.filaId;
    }

    public void setFilaId(String filaId) {
        this.filaId = filaId;
    }

    @Column(name = "host", nullable = false, length = 200)
    public String getHost() {
        return this.host;
    }

    public void setHost(String host) {
        this.host = host;
    }

    @OneToMany(mappedBy = "auditTrail")
    public Set<AuditTrailDetail> getAuditTrailDetails() {
        return this.auditTrailDetails;
    }

    public void setAuditTrailDetails(Set<AuditTrailDetail> auditTrailDetails) {
        this.auditTrailDetails = auditTrailDetails;
    }

    @Transient
    public String getNombreUsuario() {
        return nombreUsuario;
    }

    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }

    @Transient
    public List<AuditTrailDetail> getAuditTrailList() {
        return auditTrailList;
    }

    public void setAuditTrailList(List<AuditTrailDetail> auditTrailList) {
        this.auditTrailList = auditTrailList;
    }


}
