package ni.gob.inss.barista.model.entity.auditoria;


import javax.persistence.*;
import java.io.Serializable;

/**
 * AuditTrailDetail generated by hbm2java
 * Modificado por jvillanueva el 15/08/2023
 */
@Entity
@Table(name = "audit_trail_detail", schema = "auditoria")
public class AuditTrailDetail implements Serializable {

	private static final long serialVersionUID = 1L;
	
	private long id;
	private AuditTrail auditTrail;
	private String columna;
	private String valorAnterior;
	private String valorNuevo;

	public AuditTrailDetail() {
	}

	public AuditTrailDetail(int id, AuditTrail auditTrail, String columna) {
		this.id = id;
		this.auditTrail = auditTrail;
		this.columna = columna;
	}

	public AuditTrailDetail(long id, AuditTrail auditTrail, String columna,
			String valorAnterior, String valorNuevo) {
		this.id = id;
		this.auditTrail = auditTrail;
		this.columna = columna;
		this.valorAnterior = valorAnterior;
		this.valorNuevo = valorNuevo;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ref_audit_trail", nullable = false)
	public AuditTrail getAuditTrail() {
		return this.auditTrail;
	}

	public void setAuditTrail(AuditTrail auditTrail) {
		this.auditTrail = auditTrail;
	}

	@Column(name = "columna", nullable = false, length = 50)
	public String getColumna() {
		return this.columna;
	}

	public void setColumna(String columna) {
		this.columna = columna;
	}

	@Column(name = "valor_anterior")
	public String getValorAnterior() {
		return this.valorAnterior;
	}

	public void setValorAnterior(String valorAnterior) {
		this.valorAnterior = valorAnterior;
	}

	@Column(name = "valor_nuevo")
	public String getValorNuevo() {
		return this.valorNuevo;
	}

	public void setValorNuevo(String valorNuevo) {
		this.valorNuevo = valorNuevo;
	}
}